[project]
name = "team-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-adk>=0.5.0",
    "httpx>=0.28.1",
    "jupyterlab>=4.4.2",
    "mcp[cli]>=1.8.1",
]
